ktor:
  deployment:
    port: 8080
  application:
    modules:
      - dev.sirhcvt.SerializationKt.configureSerialization
      - dev.sirhcvt.SecurityKt.configureSecurity
      - dev.sirhcvt.WebsocketsKt.configureWebsockets
      - dev.sirhcvt.RoutingKt.configureRouting
