ALTER TABLE users ADD COLUMN uid VARCHAR(255);
UPDATE users SET uid = UPPER(SUBSTRING(MD5(RANDOM()::TEXT || id::TEXT), 1, 8)) WHERE uid IS NULL;
ALTER TABLE users ALTER COLUMN uid SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT users_uid_unique UNIQUE (uid);
